require('packer-config')
require('settings')
require('colorschemes.nightfox')
require('mappings')
require('nvim-tree-config')
require('lsp-config.language-servers')
require('lsp-config.nvim-cmp')
require('barbar-config')
-- require('lualine-config')
